### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by LukeDemons** [ceph/cephfs-hadoop#32]
Through some configuration operations, it seems to be successful...

`hadoop fs -ls /`
I got these messages
```
Loading libcephfs-jni from default path: /usr/local/hadoop/lib/native
Loading libcephfs-jni: Success!
ls: Invalid argument
```

Hadoop 2.7.3 Ceph 10.2.5

Within several unchanged ops, I dont think fs API changed.... 
Any help? or some conflicts appears in new version? thx!

**Comment by zphj1987** [comment]
@LukeDemons 
check you core-site.xml config for ceph ,if the host can connect to you ceph cluster,if can't , it may hung like you see

**Comment by LukeDemons** [comment]
@zphj1987 thx, it seems that the config is correct.. I have the same config as yours

<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
  <property>
     <name>hadoop.tmp.dir</name>
     <value>/usr/local/hadoop/tmp</value>
     <description>A base for other temporary directories.</description>
  </property>
<property>
    <name>fs.defaultFS</name>
    <value>ceph://192.168.0.21:6789</value>
  </property>
  <property>
    <name>fs.ceph.impl</name>
    <value>org.apache.hadoop.fs.ceph.CephFileSystem</value>
  </property>
  <property>
    <name>fs.AbstractFileSystem.ceph.impl</name>
    <value>org.apache.hadoop.fs.ceph.CephFs</value>
  </property>
</configuration>

and it says "operation not supported" instead of hunging... any ideas?

**Comment by LukeDemons** [comment]
I took a glance at ceph mon log... it says "client did not provide supported auth type", then I put keyring in hadoop core-site.xml. The error message changes from "Operation not supported" to "Invalid argument"...
I reckon that libcephfs_jni.cc may have some bugs or my cluster have some other config errors...

**Comment by noahdesu** [comment]
There should be a configuration option for passing through explicit references to the auth keys (or just to the ceph.conf if that contains pointers to the keys). It may be the case that the auth method has changed for libcephfs. In fact that actually sounds most likely. Are you able to interact with CephFS using fuse or the kernel client, just as a sanity check?

**Comment by LukeDemons** [comment]
@noahdesu thanks for your comment, I can mount CephFS using fuse normally... According to  http://docs.ceph.com/docs/master/cephfs/hadoop/ I put "ceph.auth.id, ceph.auth.keyfile" in hadoop core-site.xml. The error message changes to "Invalid argument"..  Here is my config now.

```
<configuration>
    <property>
         <name>hadoop.tmp.dir</name>
         <value>/usr/local/hadoop/tmp</value>
         <description>A base for other temporary directories.</description>
     </property>
  <property>
    <name>fs.defaultFS</name>
    <value>ceph://192.168.0.21:6789</value>
  </property>
  <property>
    <name>fs.ceph.impl</name>
    <value>org.apache.hadoop.fs.ceph.CephFileSystem</value>
  </property>
  <property>
    <name>fs.AbstractFileSystem.ceph.impl</name>
    <value>org.apache.hadoop.fs.ceph.CephFs</value>
  </property>

  <property>
    <name>ceph.auth.id</name>
    <value>admin</value>
  </property>
  <property>
    <name>ceph.auth.keyfile</name>
    <value>/etc/ceph/ceph.client.admin.keyring</value>
  </property>
</configuration>
```

`hdfs dfs -ls /`
here is some console log

```
17/03/02 13:38:25 DEBUG impl.MetricsSystemImpl: UgiMetrics, User and group related metrics
17/03/02 13:38:25 DEBUG util.KerberosName: Kerberos krb5 configuration not found, setting default realm to empty
17/03/02 13:38:25 DEBUG security.Groups:  Creating new Groups object
17/03/02 13:38:25 DEBUG util.NativeCodeLoader: Trying to load the custom-built native-hadoop library...
17/03/02 13:38:25 DEBUG util.NativeCodeLoader: Loaded the native-hadoop library
17/03/02 13:38:25 DEBUG security.JniBasedUnixGroupsMapping: Using JniBasedUnixGroupsMapping for Group resolution
17/03/02 13:38:25 DEBUG security.JniBasedUnixGroupsMappingWithFallback: Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMapping
17/03/02 13:38:25 DEBUG security.Groups: Group mapping impl=org.apache.hadoop.security.JniBasedUnixGroupsMappingWithFallback; cacheTimeout=300000; warningDeltaMs=5000
17/03/02 13:38:25 DEBUG security.UserGroupInformation: hadoop login
17/03/02 13:38:25 DEBUG security.UserGroupInformation: hadoop login commit
17/03/02 13:38:25 DEBUG security.UserGroupInformation: using local user:UnixPrincipal: root
17/03/02 13:38:25 DEBUG security.UserGroupInformation: Using user: "UnixPrincipal: root" with name root
17/03/02 13:38:25 DEBUG security.UserGroupInformation: User entry: "root"
17/03/02 13:38:25 DEBUG security.UserGroupInformation: UGI loginUser:root (auth:SIMPLE)
Loading libcephfs-jni from default path: /usr/local/hadoop/lib/native
Loading libcephfs-jni: Success!
ls: Invalid argument
```

Is this still the auth problem? or something else?

**Comment by LukeDemons** [comment]
Finally! It's config error.........

the property name should be "ceph.auth.keyring" instead of "ceph.auth.keyfile"...
sorry for my carelessness..

thx for your time @zphj1987 @noahdesu
