### ISSUE TITLE
Does the hadoop plugin access the data as a cluster over the network or locally?

### ISSUE THREAD

**Issue by arisjr** [ceph/cephfs-hadoop#42]
Dear developers,

I'm new on hadoop. 

We have being running cephfs for almost two years, loading it with large files (4GB to 4TB in size). 

Now we need to process this files and we are looking on the hadoop plugin as a solution for using mapreduce.

Does the hadoop plugin access cephfs over the network as a normal cluster or I can install the hadoop's processors on every ceph node and process the data locally?

Thanks and regards,
Aristeu

**Comment by batrick** [comment]
@arisjr the approrpriate place for this question is on ceph-users:

http://lists.ceph.com/listinfo.cgi/ceph-users-ceph.com/
